// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sdk/auction/v1/tx.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the x/auction module.
type Params struct {
	// max_bundle_size is the maximum number of transactions that can be bundled
	// in a single bundle.
	MaxBundleSize uint32 `protobuf:"varint,1,opt,name=max_bundle_size,json=maxBundleSize,proto3" json:"max_bundle_size,omitempty"`
	// escrow_account_address is the address of the account that will receive a
	// portion of the bid proceeds.
	EscrowAccountAddress []byte `protobuf:"bytes,2,opt,name=escrow_account_address,json=escrowAccountAddress,proto3" json:"escrow_account_address,omitempty"`
	// reserve_fee specifies the bid floor for the auction.
	ReserveFee types.Coin `protobuf:"bytes,3,opt,name=reserve_fee,json=reserveFee,proto3" json:"reserve_fee"`
	// min_bid_increment specifies the minimum amount that the next bid must be
	// greater than the previous bid.
	MinBidIncrement types.Coin `protobuf:"bytes,4,opt,name=min_bid_increment,json=minBidIncrement,proto3" json:"min_bid_increment"`
	// front_running_protection specifies whether front running and sandwich
	// attack protection is enabled.
	FrontRunningProtection bool `protobuf:"varint,5,opt,name=front_running_protection,json=frontRunningProtection,proto3" json:"front_running_protection,omitempty"`
	// proposer_fee defines the portion of the winning bid that goes to the block
	// proposer that proposed the block.
	ProposerFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=proposer_fee,json=proposerFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"proposer_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2030683390c1e9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxBundleSize() uint32 {
	if m != nil {
		return m.MaxBundleSize
	}
	return 0
}

func (m *Params) GetEscrowAccountAddress() []byte {
	if m != nil {
		return m.EscrowAccountAddress
	}
	return nil
}

func (m *Params) GetReserveFee() types.Coin {
	if m != nil {
		return m.ReserveFee
	}
	return types.Coin{}
}

func (m *Params) GetMinBidIncrement() types.Coin {
	if m != nil {
		return m.MinBidIncrement
	}
	return types.Coin{}
}

func (m *Params) GetFrontRunningProtection() bool {
	if m != nil {
		return m.FrontRunningProtection
	}
	return false
}

// MsgAuctionBid defines a request type for sending bids to the x/auction
// module.
type MsgAuctionBid struct {
	// bidder is the address of the account that is submitting a bid to the
	// auction.
	Bidder string `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	// bid is the amount of coins that the bidder is bidding to participate in the
	// auction.
	Bid types.Coin `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid"`
	// transactions are the bytes of the transactions that the bidder wants to
	// bundle together.
	Transactions [][]byte `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (m *MsgAuctionBid) Reset()         { *m = MsgAuctionBid{} }
func (m *MsgAuctionBid) String() string { return proto.CompactTextString(m) }
func (*MsgAuctionBid) ProtoMessage()    {}
func (*MsgAuctionBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2030683390c1e9, []int{1}
}
func (m *MsgAuctionBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuctionBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuctionBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuctionBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuctionBid.Merge(m, src)
}
func (m *MsgAuctionBid) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuctionBid) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuctionBid.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuctionBid proto.InternalMessageInfo

func (m *MsgAuctionBid) GetBidder() string {
	if m != nil {
		return m.Bidder
	}
	return ""
}

func (m *MsgAuctionBid) GetBid() types.Coin {
	if m != nil {
		return m.Bid
	}
	return types.Coin{}
}

func (m *MsgAuctionBid) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

// MsgAuctionBidResponse defines the Msg/AuctionBid response type.
type MsgAuctionBidResponse struct {
}

func (m *MsgAuctionBidResponse) Reset()         { *m = MsgAuctionBidResponse{} }
func (m *MsgAuctionBidResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAuctionBidResponse) ProtoMessage()    {}
func (*MsgAuctionBidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2030683390c1e9, []int{2}
}
func (m *MsgAuctionBidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuctionBidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuctionBidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuctionBidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuctionBidResponse.Merge(m, src)
}
func (m *MsgAuctionBidResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuctionBidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuctionBidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuctionBidResponse proto.InternalMessageInfo

// MsgUpdateParams defines a request type for updating the x/auction module
// parameters.
type MsgUpdateParams struct {
	// authority is the address of the account that is authorized to update the
	// x/auction module parameters.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params is the new parameters for the x/auction module.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2030683390c1e9, []int{3}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the Msg/UpdateParams response type.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb2030683390c1e9, []int{4}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "sdk.auction.v1.Params")
	proto.RegisterType((*MsgAuctionBid)(nil), "sdk.auction.v1.MsgAuctionBid")
	proto.RegisterType((*MsgAuctionBidResponse)(nil), "sdk.auction.v1.MsgAuctionBidResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "sdk.auction.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "sdk.auction.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("sdk/auction/v1/tx.proto", fileDescriptor_cb2030683390c1e9) }

var fileDescriptor_cb2030683390c1e9 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0xbf, 0xf2, 0x6b, 0xec, 0x50, 0x24, 0x6c, 0x90, 0x2e, 0x68, 0xda, 0x5a, 0x13,
	0xd3, 0x90, 0x74, 0xd7, 0x2a, 0x12, 0xd3, 0x1b, 0x2b, 0x62, 0x4c, 0x24, 0x21, 0x4b, 0x3c, 0xe8,
	0x65, 0x33, 0xbb, 0xfb, 0xb0, 0x4c, 0xca, 0xce, 0x6c, 0x66, 0xa6, 0xb5, 0x70, 0xf4, 0xe8, 0xc9,
	0x97, 0xe0, 0xd1, 0x23, 0x07, 0x3c, 0xf9, 0x06, 0x38, 0x12, 0xe2, 0xc1, 0x78, 0x20, 0x06, 0x0e,
	0xf8, 0x32, 0xcc, 0xee, 0x4c, 0xc1, 0x1a, 0x8c, 0x7a, 0xd9, 0xec, 0x3c, 0xdf, 0xe7, 0xdf, 0x67,
	0x9e, 0x67, 0x50, 0x55, 0x44, 0x3d, 0x07, 0xf7, 0x43, 0x49, 0x18, 0x75, 0x06, 0x1d, 0x47, 0x0e,
	0xed, 0x94, 0x33, 0xc9, 0xcc, 0xeb, 0x22, 0xea, 0xd9, 0x5a, 0xb0, 0x07, 0x9d, 0x85, 0xd9, 0x98,
	0xc5, 0x2c, 0x97, 0x9c, 0xec, 0x4f, 0x79, 0x2d, 0xdc, 0x8a, 0x19, 0x8b, 0x77, 0xc0, 0xc1, 0x29,
	0x71, 0x30, 0xa5, 0x4c, 0xe2, 0xcc, 0x5f, 0x68, 0xb5, 0x16, 0x32, 0x91, 0x30, 0xe1, 0x04, 0x58,
	0x80, 0x33, 0xe8, 0x04, 0x20, 0x71, 0xc7, 0x09, 0x19, 0xa1, 0x5a, 0x9f, 0x57, 0xba, 0xaf, 0xd2,
	0xaa, 0x83, 0x96, 0xaa, 0x3a, 0x34, 0x11, 0x71, 0xd6, 0x56, 0x22, 0x62, 0x2d, 0xcc, 0xe0, 0x84,
	0x50, 0xe6, 0xe4, 0x5f, 0x65, 0x6a, 0x7e, 0x2c, 0xa2, 0xd2, 0x06, 0xe6, 0x38, 0x11, 0xe6, 0x5d,
	0x34, 0x9d, 0xe0, 0xa1, 0x1f, 0xf4, 0x69, 0xb4, 0x03, 0xbe, 0x20, 0x7b, 0x60, 0x19, 0x0d, 0xa3,
	0x35, 0xe5, 0x4d, 0x25, 0x78, 0xe8, 0xe6, 0xd6, 0x4d, 0xb2, 0x07, 0xe6, 0x12, 0x9a, 0x03, 0x11,
	0x72, 0xf6, 0xda, 0xc7, 0x61, 0xc8, 0xfa, 0x54, 0xfa, 0x38, 0x8a, 0x38, 0x08, 0x61, 0xfd, 0xd7,
	0x30, 0x5a, 0x15, 0x6f, 0x56, 0xa9, 0x2b, 0x4a, 0x5c, 0x51, 0x9a, 0xf9, 0x04, 0x4d, 0x72, 0x10,
	0xc0, 0x07, 0xe0, 0x6f, 0x01, 0x58, 0xc5, 0x86, 0xd1, 0x9a, 0xbc, 0x3f, 0x6f, 0xeb, 0xc6, 0x33,
	0x4a, 0x5b, 0x53, 0xda, 0x8f, 0x19, 0xa1, 0x6e, 0xf9, 0xf0, 0xa4, 0x5e, 0xf8, 0x70, 0xbe, 0xbf,
	0x68, 0x78, 0x48, 0x07, 0xae, 0x01, 0x98, 0x1b, 0x68, 0x26, 0x21, 0xd4, 0x0f, 0x48, 0xe4, 0x13,
	0x1a, 0x72, 0x48, 0x80, 0x4a, 0x6b, 0xe2, 0x1f, 0x92, 0x4d, 0x27, 0x84, 0xba, 0x24, 0x7a, 0x36,
	0x0a, 0x36, 0x1f, 0x21, 0x6b, 0x8b, 0x33, 0x2a, 0x7d, 0xde, 0xa7, 0x94, 0xd0, 0x38, 0xbf, 0x51,
	0xc8, 0x67, 0x67, 0xfd, 0xdf, 0x30, 0x5a, 0xd7, 0xbc, 0xb9, 0x5c, 0xf7, 0x94, 0xbc, 0x71, 0xa1,
	0x9a, 0x2f, 0x51, 0x25, 0xe5, 0x2c, 0x65, 0x02, 0x78, 0xce, 0x54, 0x6a, 0x18, 0xad, 0xb2, 0xbb,
	0x9c, 0xd5, 0xfa, 0x7a, 0x52, 0xbf, 0xa9, 0xba, 0xc9, 0x56, 0x81, 0x30, 0x27, 0xc1, 0x72, 0xdb,
	0x7e, 0x0e, 0x31, 0x0e, 0x77, 0x57, 0x21, 0x3c, 0x3e, 0x68, 0x23, 0xdd, 0xec, 0x2a, 0x84, 0xaa,
	0xb1, 0xc9, 0x51, 0xae, 0x35, 0x80, 0x6e, 0xfd, 0xed, 0xf9, 0xfe, 0xe2, 0x42, 0xb0, 0xc3, 0xc2,
	0x5e, 0x3b, 0xdb, 0xb2, 0xe1, 0xc5, 0x9e, 0xa9, 0x61, 0x35, 0x3f, 0x1b, 0x68, 0x6a, 0x5d, 0xc4,
	0x2b, 0xca, 0xea, 0x92, 0xc8, 0xbc, 0x87, 0x4a, 0x01, 0x89, 0x22, 0xe0, 0xf9, 0xd4, 0xca, 0xae,
	0x75, 0x7c, 0xd0, 0x9e, 0xd5, 0x45, 0xf4, 0x10, 0x36, 0x25, 0x27, 0x34, 0xf6, 0xb4, 0x9f, 0xb9,
	0x8c, 0x8a, 0x01, 0x89, 0xf2, 0xa9, 0xfd, 0xed, 0xed, 0x65, 0x01, 0x66, 0x13, 0x55, 0x24, 0xc7,
	0x54, 0xe0, 0xbc, 0xb6, 0xb0, 0x8a, 0x8d, 0x62, 0xab, 0xe2, 0x8d, 0xd9, 0xba, 0x0f, 0xbf, 0xbf,
	0xaf, 0x17, 0xde, 0x9c, 0xef, 0x2f, 0xea, 0x62, 0x19, 0xcf, 0xed, 0xab, 0x78, 0xc6, 0x20, 0x9a,
	0x55, 0x74, 0x63, 0xcc, 0xe0, 0x81, 0x48, 0x19, 0x15, 0xd0, 0xfc, 0x64, 0xa0, 0xe9, 0x75, 0x11,
	0xbf, 0x48, 0x23, 0x2c, 0x41, 0x2f, 0xec, 0x32, 0x2a, 0xe3, 0xbe, 0xdc, 0x66, 0x9c, 0xc8, 0xdd,
	0x3f, 0x42, 0x5f, 0xba, 0x9a, 0x4b, 0xa8, 0x94, 0xe6, 0x19, 0x34, 0xfa, 0x9c, 0x3d, 0xfe, 0x5e,
	0x6d, 0x95, 0xdf, 0x9d, 0xc8, 0xb8, 0x3d, 0xed, 0xdb, 0xed, 0x8e, 0x88, 0x2e, 0x33, 0x65, 0x50,
	0x77, 0x7e, 0x03, 0xf5, 0x73, 0xa7, 0xcd, 0x79, 0x54, 0xfd, 0xc5, 0x34, 0x02, 0x73, 0x9f, 0x1e,
	0x9e, 0xd6, 0x8c, 0xa3, 0xd3, 0x9a, 0xf1, 0xed, 0xb4, 0x66, 0xbc, 0x3b, 0xab, 0x15, 0x8e, 0xce,
	0x6a, 0x85, 0x2f, 0x67, 0xb5, 0xc2, 0xab, 0x76, 0x4c, 0xe4, 0x76, 0x3f, 0xb0, 0x43, 0x96, 0x38,
	0xa2, 0x47, 0xd2, 0x76, 0x02, 0x03, 0xe7, 0xaa, 0x6a, 0x72, 0x37, 0x05, 0x11, 0x94, 0xf2, 0x07,
	0xfd, 0xe0, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd5, 0x16, 0xde, 0x96, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ProposerFee.Size()
		i -= size
		if _, err := m.ProposerFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.FrontRunningProtection {
		i--
		if m.FrontRunningProtection {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.MinBidIncrement.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.ReserveFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.EscrowAccountAddress) > 0 {
		i -= len(m.EscrowAccountAddress)
		copy(dAtA[i:], m.EscrowAccountAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EscrowAccountAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.MaxBundleSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxBundleSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuctionBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuctionBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuctionBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transactions[iNdEx])
			copy(dAtA[i:], m.Transactions[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Transactions[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Bid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuctionBidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuctionBidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuctionBidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxBundleSize != 0 {
		n += 1 + sovTx(uint64(m.MaxBundleSize))
	}
	l = len(m.EscrowAccountAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.ReserveFee.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.MinBidIncrement.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.FrontRunningProtection {
		n += 2
	}
	l = m.ProposerFee.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgAuctionBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Bid.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.Transactions) > 0 {
		for _, b := range m.Transactions {
			l = len(b)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAuctionBidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBundleSize", wireType)
			}
			m.MaxBundleSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBundleSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowAccountAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowAccountAddress = append(m.EscrowAccountAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.EscrowAccountAddress == nil {
				m.EscrowAccountAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReserveFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBidIncrement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBidIncrement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrontRunningProtection", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FrontRunningProtection = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProposerFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuctionBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuctionBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuctionBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, make([]byte, postIndex-iNdEx))
			copy(m.Transactions[len(m.Transactions)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuctionBidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuctionBidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuctionBidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
